name: PaxStore

options:
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

packages:
  SideSign:
    url: https://github.com/yongshuai1013/SideSign.git
    revision: 42b4958b4b78783e0b3a40d057ad977d1b992f90
  CodeSignKit:
    url: https://github.com/mahee96/CodeSignKit.git
    branch: main

targets:
  PaxStore:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources/PaxStore
    dependencies:
      - package: SideSign
      - package: CodeSignKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.paxstore.app
      PRODUCT_NAME: PaxStore
    info:
      path: Resources/Info.plist
